name: "CI"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main
      - develop
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
      
jobs:
  call-codeql:
    uses: m3im3i/actions-template/.github/workflows/codeql-template.yaml@main
    with:
      working-repo: ${{ github.repository }}
      image-name: 'webgoat'
    secrets: inherit
  call-build:
    needs: call-codeql
    uses: m3im3i/actions-template/.github/workflows/build-template.yaml@main
    with:
      working-repo: ${{ github.repository }}
      image-name: 'webgoat'
      launguage-run: 'java'
    secrets: inherit
