name: "CI"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main
      - dev
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
      
jobs:
  call-dependency-review:
    if: github.event_name == 'pull_request'
    uses: m3im3i/actions-template/.github/workflows/depend-review-template.yaml@main
    with:
      fail-severity: 'critical'
  call-codeql:
    uses: m3im3i/actions-template/.github/workflows/codeql-template.yaml@main
    with:
      languages-torun: '[{"language": "java"},{ "language": "javascript"}]'
    secrets: inherit
  call-unittest:
    name: unit test
    runs-on: ubuntu-latest
    steps:
    - name: unit test stub 
      run: | 
        echo "unit test"
  call-build:
    needs: [call-codeql, call-dependency-review]
    uses: m3im3i/actions-template/.github/workflows/build-template.yaml@main
    continue-on-error: true
    with:
      working-repo: ${{ github.repository }}
      image-name: 'webgoat'
    secrets: inherit
