name: "CI"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main
      - dev
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
      
jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: moderate
          #
          # You can only can only include one of these two options: `allow-licenses` and `deny-licences`
          #
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          # allow-licenses: GPL-3.0, BSD-3-Clause, MIT
          #
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          # deny-licenses: LGPL-2.0, BSD-2-Clause
  call-dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    steps:
    - name: dependabot stub 
      run: | 
        echo "dependabot"  
  call-codeql:
    uses: m3im3i/actions-template/.github/workflows/codeql-template.yaml@main
    with:
      languages-torun: '[{"language": "java"},{ "language": "javascript"}]'
      #languages2-torun: '["java","javascript"]'
    secrets: inherit
  call-unittest:
    name: unit test
    runs-on: ubuntu-latest
    steps:
    - name: unit test stub 
      run: | 
        echo "unit test"
  call-build:
    needs: call-codeql
    uses: m3im3i/actions-template/.github/workflows/build-template.yaml@main
    with:
      working-repo: ${{ github.repository }}
      image-name: 'webgoat'
    secrets: inherit
